<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE persoane [
<!ATTLIST persoana id CDATA #REQUIRED>
<!ELEMENT persoane (persoana+)>
<!ELEMENT persoana (nume,prenume,varsta,adresa,facultate,profil,an,job)>
<!ELEMENT nume (#PCDATA)>
<!ELEMENT prenume (#PCDATA)>
<!ELEMENT varsta (#PCDATA)>
<!ELEMENT adresa (#PCDATA)>
<!ELEMENT facultate (#PCDATA)>
<!ELEMENT profil (#PCDATA)>
<!ELEMENT an (#PCDATA)>
<!ELEMENT job (#PCDATA)>
]>

<persoane>
    <persoana id="1">
        <nume>Popescu</nume>
        <prenume>Ion</prenume>
        <varsta>23</varsta>
        <adresa>
            Șoseaua Bucium, nr. 3, Iași
        </adresa>
        <facultate>Informatică</facultate>
        <profil>info</profil>
        <an>1</an>
        <job>programator</job>
    </persoana>
    <persoana id="2">
        <nume>Balan</nume>
        <prenume>Marius</prenume>
        <varsta>22</varsta>
        <adresa>
            Șoseaua Națională nr. 43F, bl. A2, sc. D, Iași
        </adresa>
        <facultate>AC</facultate>
        <profil>CTI</profil>
        <an>3</an>
        <job>Front End Developer</job>
    </persoana>
    <persoana id="3">
        <nume>Balan</nume>
        <prenume>Daniel</prenume>
        <varsta>22</varsta>
        <adresa>
            Șoseaua Națională nr. 43F, bl. A2, sc. D, Iași
        </adresa>
        <facultate>AC</facultate>
        <profil>IS</profil>
        <an>3</an>
        <job>SWD</job>
    </persoana>
    <persoana id="4">
        <nume>Zălincă</nume>
        <prenume>Claudiu</prenume>
        <varsta>21</varsta>
        <adresa>
            Bulevardul Eroilor, bl. C4, București
        </adresa>
        <facultate>AC</facultate>
        <profil>info</profil>
        <an>4</an>
        <job>SoftDev</job>
    </persoana>
    <persoana id="5">
        <nume>Bogdan</nume>
        <prenume>Vasile</prenume>
        <varsta>27</varsta>
        <adresa>
            Str. Eminescu, nr. 3, Suceava
        </adresa>
        <facultate>ETTI</facultate>
        <profil>Telecomunicații</profil>
        <an>4</an>
        <job>Call center</job>
    </persoana>
</persoane>

